### ISSUE TITLE
Sentry run logo offer

### ISSUE THREAD

**Issue by cryptogadget** [faustinoaq/sentry-run#2]
Hi sir. I want to contribute for sentry run. I degined a simple logo for readme file.

 If you want it, i will send a pull-request. Please fedback me. Good works!

![sentry-run](https://user-images.githubusercontent.com/40358165/41542252-316c7932-731d-11e8-9183-7a7b548b456f.jpg)

**Comment by faustinoaq** [comment]
Awesome!!! :tada:

**Comment by cryptogadget** [comment]
Thanks a lot :) Please check the pull-request. 

https://github.com/faustinoaq/sentry-run/pull/3
